main: tld.example.myplugin.Main
name: Fireball Plugin
version: 1.0
author: KingCloudNinja
description: Fireball Plugin
commands:
  fb:
    description: Fires a fireball
    usage: 
    permission: server.fireball
    permission-message: Unknown command. type "/help" for help.
  about:
    description: About the plugin.
    usage: 
    permission: server.all
    permission-message: Unknown command. type "/help" for help.
