main: tld.example.myplugin.Main
name: ScorchingPVP
version: 1.0
author: ScorchingPVP
description: ScorchingPVP Plugin
commands:
  fb:
    description: Fires a fireball
    usage: 
    permission: server.fireball
    permission-message: Unknown command. type "/help" for help.
  about:
    description: About the plugin.
    usage: 
    permission: server.all
    permission-message: Unknown command. type "/help" for help.
